---
apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    env: test
spec:
  containers:
  - name: python
    image: arjunachari12/my-python-image
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: python-app-rc
  labels:
    env: test
spec:
  replicas: 5
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
      - name: python
        image: arjunachari12/my-python-image
